version: '3'
services:
  database:
    container_name: befreejenkinsdb
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: befree
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3307"
    networks:
      - test_network

  web:
    container_name: befreejenkinsapi
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://befreedb:3307/befree?useUnicode=true&characterEncoding=UTF-8&characterSetResult=UTF8&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    depends_on:
      - database
    networks:
      - test_network

networks:
  test_network:
